### ISSUE TITLE
Questions regarding the dataset and the related paper

### ISSUE THREAD

**Issue by gianniskazakos** [skynbe/Refer-Youtube-VOS#1]
Hi! Thank you for this great dataset and congratulations for the related paper!

I am doing my Master thesis on this topic and I would like to ask you some questions regarding the data.

I saw that in many cases there is more than one referring expression for the same object (both in first frame and full video annotations). Is there any difference between them, or were the annotators asked to provide more than one referring expression?

And also which of them (referring expressions) did you use for training and evaluating your models, in case I want to compare with your results in the related paper?

Finally, are you planning to release any code for the proposed model URVOS?

Thank you in advance

**Comment by skynbe** [comment]
Hi! 

We ask multiple annotators to annotate language annotations, resulting in multiple language expressions for every single object. 

We use all of them for training and evaluation in the main paper. You can find the ablation study on the annotation type (full-video and first-frame each) in Table 1 of the supplementary material.

We're planning to release our codes, but it may take some time. I think it can help if you refer to STM(https://github.com/seoungwugoh/STM) and CMSA(https://github.com/lwye/CMSA-Net).

Thanks and regards.
