### ISSUE TITLE
A consultation on the release of the baseline code?

### ISSUE THREAD

**Issue by Starboy-at-earth** [skynbe/Refer-Youtube-VOS#4]
Dear author:
Thank you for your significant contribution to the language guided Video Object Segmentation methods!!! Do you have any accurate date to publish the code? My email is 2667004002@qq.com.

**Comment by skynbe** [comment]
I'm sorry for the late reply due to the late notification. I have just uploaded the baseline codes (which are not URVOS, just a baseline code.)
