### ISSUE TITLE
About the meta_expression.json file

### ISSUE THREAD

**Issue by SAMSTAYREAL** [skynbe/Refer-Youtube-VOS#5]
I found that the meta_expressions.json of this baseline project is different from the original version provided in the official website,could you please share the 'meta_expressions.json' file? Thanks a lot.

**Comment by skynbe** [comment]
Sorry for the late reply. Here is the original version of meta_expressions.json file.

[meta_expressions_train.json.zip](https://github.com/skynbe/Refer-Youtube-VOS/files/10077151/meta_expressions_train.json.zip)
